# Generated by Django 5.0.14 on 2025-06-30 22:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_subscription_delete_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-subscribed_at']},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscribed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['email'], name='newsletter__email_3ce146_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['-subscribed_at'], name='newsletter__subscri_e4a0d3_idx'),
        ),
    ]
